// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: '.NET Thailand',
      social: {
        github: 'https://github.com/dotnetthailand',
        facebook: 'https://www.facebook.com/groups/dotnetthailand',
      },
      sidebar: [
        { label: 'Home', slug: '' },
        { label: 'Contributors', slug: 'contributors' },
        { label: 'เว็บไซต์พันธมิตร', slug: 'friends-of-dotnet-thailand' },
        { label: 'รวมฟรีหนังสือ, วิดีโอ และแหล่งความรู้การเขียนโปรแกรม', slug: 'free-programming-ebooks-tutorials-and-resources' },
        {
          label: 'Suggested social network accounts for developers to follow',
          slug: 'suggested-social-network-accounts-for-developers-to-follow'
        },
        { label: 'Privacy policy', slug: 'privacy-policy' },
        {
          label: '.NET FAQ',
          // https://starlight.astro.build/guides/sidebar/#collapsing-groups
          // Do not collapse the "Constellations" group but collapse its
          // autogenerated subgroups.
          collapsed: false,
          autogenerate: { directory: 'faq', collapsed: true },
        },
        {
          label: 'Web frameworks',
          collapsed: false,
          autogenerate: { directory: 'web-frameworks', collapsed: true },
        },
        {
          label: 'Storage',
          collapsed: false,
          autogenerate: { directory: 'storage', collapsed: true },
        },
        {
          label: 'Testing',
          collapsed: false,
          autogenerate: { directory: 'testing', collapsed: true },
        },
        {
          label: 'Front-end web',
          collapsed: false,
          autogenerate: { directory: 'frontend-web', collapsed: true },
        },
        {
          label: 'Cloud hosting',
          collapsed: false,
          autogenerate: { directory: 'cloud-hosting', collapsed: true },
        },
        {
          label: 'Programming cookbook',
          collapsed: false,
          autogenerate: { directory: 'programming-cookbook', collapsed: true },
        },
        {
          label: 'To other lanaguages',
          collapsed: false,
          autogenerate: { directory: 'to-other-languages', collapsed: true },
        },
        {
          label: 'Awesome .NET Thailand projects',
          collapsed: false,
          autogenerate: { directory: 'awesome-dotnet-thailand-projects', collapsed: true },
        },
        {
          label: '3rd party API',
          collapsed: false,
          autogenerate: { directory: '3rd-party-api', collapsed: true },
        },
      ],
      customCss: [
        // Relative path to your custom CSS file
        './src/styles/custom.scss',
      ],
    }),
    react(),
  ],
  vite: {
    ssr: { noExternal: ['styled-components'] },
  },

});
