// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: '.NET Thailand',
      social: {
        github: 'https://github.com/dotnetthailand',
      },
      sidebar: [
        {
          label: 'Guides',
          items: [
            // Each item here is one entry in the navigation menu.
            { label: 'Example Guide', slug: 'guides/example' },
          ],
        },
        {
          label: 'Reference',
          autogenerate: { directory: 'reference' },
        },
        {
          label: 'FAQ',
          // https://starlight.astro.build/guides/sidebar/#collapsing-groups
          // Do not collapse the "Constellations" group but collapse its
          // autogenerated subgroups.
          collapsed: false,
          autogenerate: { directory: 'faq', collapsed: true },
        },
      ],
      customCss: [
        // Relative path to your custom CSS file
        './src/styles/custom.scss',
      ],
    }),
    react(),
  ],
});
