metadata:
  name: .NET Thailand
  short_name: .NET Thailand
  description: .NET Thailand community
  language: en
  pathPrefix: / # https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/
  siteImage: /assets/dotnetthailand-ogimage-dark.png
  favicon: /assets/favicon.png
  themeColor: '#ff0000'
  uaTrackingId: UA-204153201-1
  siteUrl: https://www.dotnetthailand.com/
header:
  enabled: true
  logo: /assets/code.svg
  logoLink: /
  helpUrl: ''
  links:
    - text: Home
      link: /
      external: false
    - text: .NET Thailand group
      link: https://www.facebook.com/groups/dotnetthailand
      external: true
    - text: Credit to our contributors
      link: /contributors
      external: false
sidebar:
  enabled: true
  expanded: false

  # Table of content
  groups:
    - order: 0
      path: /faq
      # Get emoji from https://emojipedia.org/github/
      title: ':question: .NET FAQ'

    - order: 1
      path: /web-frameworks
      title: ':fire: Web Frameworks'

    - order: 2
      path: /storage
      title: ':floppy_disk: storage'

    - order: 3
      path: /testing
      title: ':heavy_check_mark: Testing'

    - order: 4
      path: /frontend-web
      title: ':iphone: Front-end Web'

    - order: 5
      path: /cloud-hosting
      title: ':cloud: Cloud & Hosting'

    - order: 6
      path: /programming-cookbook
      title: ':blue_book: Programming cookbook'

    - order: 7
      path: /to-other-languages
      title: ':bicyclist: To other languages'

    - order: 8
      path: /awesome-dotnet-thailand-projects
      title: ':package: Awesome .NET Thailand Projects'

    - order: 9
      path: /3rd-party-api
      title: ':briefcase: 3rd party API'

  links:
    - text: .NET Thailand
      link: https://www.facebook.com/groups/dotnetthailand
    - text: React
      link: https://reactjs.org

  ignoreIndex: false
  poweredBy:
    trademark: /assets/gatsby.png
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: /assets/favicon.png
    name: .NET Thailand
    short_name: .NET Thailand

social:
  github: https://github.com/dotnetthailand/dotnetthailand.github.io
  facebook: https://www.facebook.com/groups/dotnetthailand

features:
  content:
    rootPath: content
  darkMode:
    enabled: true
    default: false
  editOnRepo:
    location: https://github.com/dotnetthailand/dotnetthailand.github.io
    type: github
    editable: true
    repo: dotnetthailand/dotnetthailand.github.io
  mermaid:
    language: mermaid
    # Supported theme are 'dark', 'neutral', 'forrest', or 'default'
    theme: default
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - /configuration/settingup/features
    excludePaths:
      - /
    height: 3
    prependToBody: false
    color: '#A05EB5'
  previousNext:
    enabled: false
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: 2020, Mateusz Filipowicz
    webMaster: Mateusz Filipowicz
    managingEditor: Mateusz Filipowicz
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: ^/
    outputPath: /rss.xml
    generator: boogi
  scrollTop: true
  search:
    enabled: true
    engine: algolia
    placeholder: Search
    startComponent: icon
    excerptSize: 20000
    debounceTime: 450
    snippetLength: 23
    hitsPerPage: 8
    showStats: true
    pagination:
      enabled: true
      totalPages: 3
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode:
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
  facebookSDK:
    appId: '891898928268139'
